.github/actions/check-release/action.yml, .github/actions/draft-changelog/action.yml, .github/actions/draft-release/action.yml, .github/workflows/check-release.yml, jupyter_releaser/actions/publish_release.py, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/test_functions.py
Fixes jupyter-server/jupyter_releaser#9
=> Allow Check Release to be Run on Fork PRs

.github/actions/draft-changelog/action.yml, .github/actions/draft-release/action.yml, .github/actions/publish-release/action.yml, .github/workflows/draft-changelog.yml, .github/workflows/draft-release.yml, .github/workflows/publish-release.yml, .gitignore, jupyter_releaser/changelog.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_functions.py
- Do not pass `until` to `github_activity` since it excludes that commit
- Use `__token__` as the default twine username
- Use `@v1` tag instead of local installs for the manual workflows so the fork is always running the latest from the source `jupyter_releaser`
- Fix bug where `git stash` is applied when there are no changes (which raises an error)
=> Pre-release clean up

.github/workflows/check-release.yml, .github/workflows/draft-changelog.yml, .github/workflows/draft-release.yml, .github/workflows/publish-release.yml, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py
Use force when fetching tags in the checkout.
Addresses https://github.com/jupyter-server/jupyter_releaser/runs/2482074319?check_suite_focus=true
Also fixes misspelling of releaser repo in workflows
Install node in all workflows
=> More Cleanup

.github/workflows/publish-release.yml, README.md, jupyter_releaser/lib.py, jupyter_releaser/npm.py, jupyter_releaser/python.py
- Target the production PYPI and NPM servers
- Do not recommend `jupyter_packaging` as a runtime requirement
- Update docs on tokens
- Clean up PyPI setup - allow registry to be set, refactor, only start pypi server if uploading python package
- Allow npm registry to be set, only set config when uploading npm package
- Add docs on keeping the fork up to date
=> Prep for PyPI Release

.github/actions/draft-changelog/action.yml, .github/actions/draft-release/action.yml, .github/workflows/draft-changelog.yml, .github/workflows/draft-release.yml, README.md, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py
This parameter is useful when making a final release after a series of pre-releases, to include all of the PRs from the pre-releases.
=> Add Support for Since Parameter

CHANGELOG.md
Automated Changelog Entry for 0.1.1 on master
| Version Spec | 0.1.1 |
=> Automated Changelog Entry for 0.1.1 on master

CHANGELOG.md
Automated Changelog Entry for 0.1.2 on master
| Version Spec | 0.1.2 |
=> Automated Changelog Entry for 0.1.2 on master

.github/actions/check-release/action.yml
NPM-Only Packages use `npm version <version_spec>`, and the default value of `0.0.1a0` is not a valid npm version.
=> Fix Check Release for NPM-Only Packages

jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/npm.py, jupyter_releaser/tests/conftest.py, jupyter_releaser/tests/test_functions.py, setup.cfg
* Do not require tags to exist in the branch for changelog generation
* Skip `node_modules` files when checking links
* Print current changelog entry in `draft_changelog`
* Handle `workspaces` metadata being a dict (`jupyterlab` currently) or a list (`lumino` currently)
* Pin `tomlkit` since it `0.7.1` breaks `tbump`
=> More Cleanup in Preparation for Usage with Lumino

jupyter_releaser/cli.py, jupyter_releaser/npm.py, jupyter_releaser/tests/conftest.py, jupyter_releaser/tests/test_cli.py
- Do not require packages to be importable by node (they might contain DOM code or be style-only). Instead, if a "main" attribute exists, make sure the file is available in the dist
- Normalize handling of workspaces using a helper function
=> More Changes Needed to Support Lumino

jupyter_releaser/lib.py, jupyter_releaser/util.py
Follows the same pattern as python packages, part of the work to add releaser to Lumino
=> Properly install NPM Packages

.github/scripts/bump_tag.sh, pyproject.toml
Avoids the manual step of updating the `v1` tag for GitHub Actions consumers as part of the release process of `jupyter_releaser`.
=> Use Releaser to Tag Itself

CHANGELOG.md
Automated Changelog Entry for 0.1.6 on master
| Version Spec | 0.1.6 |
=> Automated Changelog Entry for 0.1.6 on master

jupyter_releaser/npm.py
To fetch the name of the npm tarball, which should be the last statement of the `npm pack` output.
As noticed in https://github.com/jupyterlab/extension-cookiecutter-ts/issues/162#issuecomment-864242628
=> Use the last line of the `npm pack` command

jupyter_releaser/npm.py
Fixes #38.  Follow up to fix a logic error introduced in https://github.com/jupyter-server/jupyter_releaser/pull/34. We must use the given registry value before modifying it for token auth usage.
=> Fix usage of registry value

CHANGELOG.md
Automated Changelog Entry for 0.1.8 on master
| Version Spec | 0.1.8 |
=> Automated Changelog Entry for 0.1.8 on master

.github/workflows/publish-release.yml
Debugging the failing workflow mentioned in https://github.com/jupyter-server/jupyter_releaser/issues/38 let to log the content of `.npmrc` which looked like the following:
=> Remove extra dollar sign for registry inputs

jupyter_releaser/lib.py, jupyter_releaser/npm.py
Since the publish command is run from `dist_dir`.
And it seems that `npm` would otherwise ignore the `.npmrc` file from a parent folder.
=> Write .npmrc to dist_dir

CHANGELOG.md
Automated Changelog Entry for 0.1.9 on master
| Version Spec | 0.1.9 |
=> Automated Changelog Entry for 0.1.9 on master

CHANGELOG.md
Automated Changelog Entry for 0.1.11 on master
| Version Spec | 0.1.11 |
=> Automated Changelog Entry for 0.1.11 on master

jupyter_releaser/npm.py
Ensure each sub-package is a directory and has a `package.json` file.
=> Fix Handling of Workspace Packages

jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/npm.py, jupyter_releaser/tests/test_cli.py
Seen while working on https://github.com/jupyterlab/jupyterlab/issues/10340
- Install in editable mode to pick up dev assets
- Allow options to be passed to `npm install`, which include `--legacy-peer-deps` for JupyterLab
=> More fixups

CHANGELOG.md
Automated Changelog Entry for 0.1.12 on master
| Version Spec | 0.1.12 |
=> Automated Changelog Entry for 0.1.12 on master

jupyter_releaser/npm.py
Follow up to https://github.com/jupyter-server/jupyter_releaser/pull/53 to fix all usages of workspace paths.
=> Fix handling of workspace paths

.github/actions/check-release/action.yml, jupyter_releaser/cli.py, jupyter_releaser/util.py
Provide reasonable defaults for version bump but allow it to be overridden.
Needed for jupyterlab/jupyterlab#10340 (https://github.com/jupyterlab/jupyterlab/issues/10340)
=> Fix handling of default version bump

CHANGELOG.md
Automated Changelog Entry for 0.1.13 on master
| Version Spec | 0.1.13 |
=> Automated Changelog Entry for 0.1.13 on master

CHANGELOG.md
Automated Changelog Entry for 0.1.14 on master
| Version Spec | 0.1.14 |
=> Automated Changelog Entry for 0.1.14 on master

jupyter_releaser/lib.py
Handle the case where there are no changes to the changelog, which can happen when making an automated changelog pull request. Fixes error seen in https://github.com/jupyter-server/jupyter_releaser/actions/runs/1005457462.
=> Handle the case where there are no changes in changelog

CHANGELOG.md
Automated Changelog Entry for 0.1.15 on master
| Version Spec | 0.1.15 |
=> Automated Changelog Entry for 0.1.15 on master

setup.cfg
Pin versions until a new release of `tbump` with https://github.com/dmerejkowsky/tbump/pull/105 is released.
=> Pin versions

CHANGELOG.md
Automated Changelog Entry for 0.1.16 on master
| Version Spec | 0.1.16 |
=> Automated Changelog Entry for 0.1.16 on master

.github/actions/check-release/action.yml, jupyter_releaser/actions/draft_release.py
Start with a fresh git checkout after drafting the changelog, to prevent any other state from leaking between `draft_changelog` and `draft_release`.  Extract just the changelog file and insert it into the new checkout directory.
See relevant failure [here](https://github.com/jupyterlab/galata/pull/73/checks?check_run_id=3085102485)
=> Improve Check Release Isolation

jupyter_releaser/actions/draft_release.py
Caught when running the Draft Release workflow: https://github.com/jtpio/jupyter_releaser/runs/3086332621?check_suite_focus=true
=> Add default for `RH_IS_CHECK_RELEASE`

.github/workflows/check-release.yml, jupyter_releaser/actions/draft_release.py, jupyter_releaser/lib.py, jupyter_releaser/util.py, setup.cfg
- Pin setuptools to the current major version
- Sort released packages by name
- Only include the dist file name in the release commit message
- Move check link to the end of draft release since it less likely to cause failures and can be long
- Use supported flag name for pytest to avoid warnings
- Add nightly cron job for the check release workflow
=> Even more cleanup

CHANGELOG.md
Automated Changelog Entry for 0.2.0 on master
| Version Spec | 0.2.0 |
=> Automated Changelog Entry for 0.2.0 on master

jupyter_releaser/actions/draft_release.py
=> Restore guard to pip install if releaser

CHANGELOG.md
Automated Changelog Entry for 0.2.1 on master
| Version Spec | 0.2.1 |
=> Automated Changelog Entry for 0.2.1 on master

.github/actions/check-release/action.yml, LICENSE, jupyter_releaser/actions/draft_release.py, jupyter_releaser/tee.py, jupyter_releaser/util.py
Use https://github.com/pycontribs/subprocess-tee to get asynchronous subprocess output for all platforms but Windows, which does not work well with asynchronous processes in Python.
Also clean up logic for when to install `jupyter-releaser` in the workflows.
=> Use Async Output Where Possible

jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py
Handle error message seen in [lumino release](https://github.com/blink1073/jupyter_releaser/runs/3102706029?check_suite_focus=true) that differs from the previously used error message for a conflicting package.
=> Better Handling of Already Existing Packages

CHANGELOG.md
Automated Changelog Entry for 0.2.2 on master
| Version Spec | 0.2.2 |
=> Automated Changelog Entry for 0.2.2 on master

jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/util.py
Follow up to jupyter-server/jupyter_releaser#77, addresses error seen in publish workflow
=> Fix handling of error output

CHANGELOG.md
Automated Changelog Entry for 0.2.3 on master
| Version Spec | 0.2.3 |
=> Automated Changelog Entry for 0.2.3 on master

CHANGELOG.md
Automated Changelog Entry for 0.2.4 on master
| Version Spec | 0.2.4 |
=> Automated Changelog Entry for 0.2.4 on master

README.md, jupyter_releaser/cli.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py
Add the ability to skip commands by name.  Can be used to move pieces like `check_link`s to another build to shorten release time.
Can be used to skip problematic sections (for example an `npm-check` in a Python package that would have caused problems).
=> Add ability to skip steps

jupyter_releaser/cli.py
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/67, allowing the use of after-git-prep hooks.
=> Allow after-prep-git to work

jupyter_releaser/actions/draft_release.py
Add an extra changelog check before pushing commits and tags to ensure no PRs were merged during release process
=> Add extra changelog check before push

CHANGELOG.md
Automated Changelog Entry for 0.3.0 on master
| Version Spec | 0.3.0 |
=> Automated Changelog Entry for 0.3.0 on master

.github/actions/check-release/action.yml
Fix branch names like ft/foo or fix/bar
This happens there for example: https://github.com/fcollonval/lumino/runs/3163528043?check_suite_focus=true
```
+ echo 'Using GITHUB_REF: refs/heads/ft/accordion-panel'
Using GITHUB_REF: refs/heads/ft/accordion-panel
++ cut -d/ -f 3
++ echo refs/heads/ft/accordion-panel
+ export RH_BRANCH=ft
+ RH_BRANCH=ft
```
=> support structured branch name

CHANGELOG.md
Automated Changelog Entry for 0.3.2 on master
| Version Spec | 0.3.2 |
=> Automated Changelog Entry for 0.3.2 on master

jupyter_releaser/actions/draft_release.py
Fixes bug introduced in jupyter-server/jupyter_releaser#91
=> Fix Handling of Tag Lock

CHANGELOG.md
Automated Changelog Entry for 0.3.3 on master
| Version Spec | 0.3.3 |
=> Automated Changelog Entry for 0.3.3 on master

jupyter_releaser/actions/draft_release.py
Follow up to jupyter-server/jupyter_releaser#93 to handle the case where there are no tags on the branch.
=> More cleanup of tag lock

CHANGELOG.md
Automated Changelog Entry for 0.3.4 on master
| Version Spec | 0.3.4 |
=> Automated Changelog Entry for 0.3.4 on master

.github/actions/check-links/action.yml, .github/workflows/check-release.yml, .github/workflows/test.yml, jupyter_releaser/cli.py, pyproject.toml
This allows other repos to use `skip = "check-links"` and then use this action.
=> Add an action for check-links

CHANGELOG.md
Automated Changelog Entry for 0.4.3 on master
| Version Spec | 0.4.3 |
=> Automated Changelog Entry for 0.4.3 on master

.github/workflows/generate-changelog.yml, .github/workflows/test.yml, jupyter_releaser/actions/generate-changelog.py, jupyter_releaser/changelog.py
Adds a manual workflow to generate a changelog entry
for a repo that either does not use `jupyter_releaser` or
requires a changelog entry for an older release.
Also supports changelogs written in RST.
=> Add Generate Changelog Workflow

CHANGELOG.md
Automated Changelog Entry for 0.4.4 on master
| Version Spec | 0.4.4 |
=> Automated Changelog Entry for 0.4.4 on master

jupyter_releaser/actions/draft_release.py
Fixes capture of `RH_SINCE` that was disrupted by https://github.com/jupyter-server/jupyter_releaser/pull/106
=> Fix handling of "since" parameter

jupyter_releaser/actions/draft_changelog.py, jupyter_releaser/actions/draft_release.py
Fix handling of `since` parameter for the `draft_changelog` action, which has been causing failing builds in [jupyterlab](https://github.com/jupyterlab/jupyterlab/actions/runs/1143317194).
=> Fix Create Changelog Action

CHANGELOG.md
Automated Changelog Entry for 0.4.5 on master
| Version Spec | 0.4.5 |
| Since | v1 |
=> Automated Changelog Entry for 0.4.5 on master

CHANGELOG.md
Automated Changelog Entry for 0.4.6 on master
| Version Spec | 0.4.6 |
| Since | v1 |
=> Automated Changelog Entry for 0.4.6 on master

jupyter_releaser/actions/draft_changelog.py, jupyter_releaser/actions/draft_release.py
Fixes bug introduced in jupyter-server/jupyter_releaser#116
=> Restore capture of since parameter

CHANGELOG.md
Automated Changelog Entry for 0.4.7 on master
| Version Spec | 0.4.7 |
| Since | v1 |
=> Automated Changelog Entry for 0.4.7 on master

CHANGELOG.md
Automated Changelog Entry for 0.5.0 on master
| Version Spec | 0.5.0 |
| Since | v1 |
=> Automated Changelog Entry for 0.5.0 on master

CHANGELOG.md
Automated Changelog Entry for 0.5.2 on master
| Version Spec | 0.5.2 |
| Since | v1 |
=> Automated Changelog Entry for 0.5.2 on master

jupyter_releaser/lib.py
This is more of a personal preference, but maybe we could drop the "Release" prefix in the GitHub Release title?
=> Remove "Release" from the GitHub Release title

MANIFEST.in, jupyter_releaser/schema.json, jupyter_releaser/util.py, setup.cfg
Add a JSON schema for allowed config options and use it to validate user options.
=> Add JSON Schema for Config

CHANGELOG.md
Automated Changelog Entry for 0.6.0 on master
| Version Spec | 0.6.0 |
| Since | v1 |
=> Automated Changelog Entry for 0.6.0 on master

jupyter_releaser/util.py, setup.cfg
This should help fix an issue noticed when trying to release the releaser.
Example run: https://github.com/jtpio/jupyter_releaser/runs/3542239326
=> Use `importlib_resources` to read `schema.json`

CHANGELOG.md
Automated Changelog Entry for 0.6.1 on master
| Version Spec | 0.6.1 |
| Since | v1 |
=> Automated Changelog Entry for 0.6.1 on master

jupyter_releaser/lib.py
This should fix some of the automated changelog entries reporting one version behind for the `npm` packages.
This is the case for version commands that do not commit their changes. In that case the changes would be discarded.
For example this one: https://github.com/jupyterlab/retrolab/pull/217
=> Read npm versions before `git checkout -- .`

CHANGELOG.md
Automated Changelog Entry for 0.6.2 on master
| Version Spec | 0.6.2 |
| Since | v1 |
=> Automated Changelog Entry for 0.6.2 on master

jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py
Make the tag name used for the release configurable.
Also fix a log message that was using the wrong step name.
=> Make tag name configurable

.github/workflows/publish-release.yml, README.md, jupyter_releaser/actions/publish_release.py
Fixes #36 
Use a token map to map github repos to pypi tokens.
=> Add support for PYPI token map

.github/actions/draft-changelog/action.yml, .github/actions/draft-release/action.yml, .github/workflows/draft-changelog.yml, .github/workflows/draft-release.yml, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/test_functions.py
Add an option to use PRs with activity since the last stable git tag. This is useful for creating the first alpha release or first final release in a release cycle.
=> Add Since Last Stable Option for Changelog

.github/workflows/autopublish-release.yml, .github/workflows/draft-release.yml
Fixes #148.
Adds a new input setting to "Draft Release" for `auto_publish` that defaults to `true`.
Uses dependent workflows to pass the draft GitHub release url to the "Auto Publish Release" workflow if `auto_publish` is selected.
=> Enable Auto Publish

CHANGELOG.md
Automated Changelog Entry for 0.7.0 on master
| Version Spec | 0.7.0 |
| Since | v1 |
=> Automated Changelog Entry for 0.7.0 on master

jupyter_releaser/actions/publish_release.py
Follow up to #146 to handle the fact that we do not have a `GH_REPOSITORY` target during the publish workflow.
=> Fix handling of PYPI token map

CHANGELOG.md
Automated Changelog Entry for 0.7.1 on master
| Version Spec | 0.7.1 |
| Since | v1 |
=> Automated Changelog Entry for 0.7.1 on master

CHANGELOG.md
Automated Changelog Entry for 0.7.2 on master
| Version Spec | 0.7.2 |
| Since | v1 |
=> Automated Changelog Entry for 0.7.2 on master

CHANGELOG.md
Automated Changelog Entry for 0.7.3 on master
| Version Spec | 0.7.3 |
| Since | v1 |
=> Automated Changelog Entry for 0.7.3 on master

CHANGELOG.md
Automated Changelog Entry for 0.7.4 on master
| Version Spec | 0.7.4 |
| Since | v1 |
=> Automated Changelog Entry for 0.7.4 on master

README.md
Fixes #135 
Adding this small snippet to the docs in the README. Maybe we'll want to bake that in the check release action directly but for now it's also fine as a separate step.
=> Document uploading release assets as artifacts

.github/workflows/test.yml, MANIFEST.in, docs/Makefile, docs/environment.yml, docs/make.bat, docs/source/conf.py, docs/source/index.rst, pyproject.toml, readthedocs.yml
Add skeleton for sphinx docs and RTD support
=> Add Sphinx Docs

jupyter_releaser/python.py
Strip whitespace from the token and print the last five characters for debugging purposes.
=> Debug token map handling

CHANGELOG.md
Automated Changelog Entry for 0.7.5 on master
| Version Spec | 0.7.5 |
| Since | v1 |
=> Automated Changelog Entry for 0.7.5 on master

CHANGELOG.md
Automated Changelog Entry for 0.7.6 on master
| Version Spec | 0.7.6 |
| Since | v1 |
=> Automated Changelog Entry for 0.7.6 on master

CHANGELOG.md
Automated Changelog Entry for 0.9.0 on master
| Version Spec | 0.9.0 |
| Since | v1 |
=> Automated Changelog Entry for 0.9.0 on master

.github/actions/draft-changelog/action.yml, .github/actions/draft-release/action.yml, .github/actions/publish-release/action.yml
Follow up to https://github.com/jupyter-server/jupyter_releaser/pull/184. Since all of the actions are used by other repos, we need to use the v1 tag for all sibling action calls.
=> Make all of the actions use v1 tag internally

jupyter_releaser/actions/publish_release.py
Publishing a release seems to be failing on repos with a default branch not named `master` at the `forwardport-changelog` step.
Example run for a repo with `main` as the default branch: https://github.com/jtpio/jupyter_releaser/runs/3951643392?check_suite_focus=true
Comparing this workflow:
To a previous successful one:
We see the releaser used to run `git remote show origin` first to retrieve the default branch.
Which seems to indicate that it was defaulting to:
https://github.com/jupyter-server/jupyter_releaser/blob/6dd044a248ba4865c4a94ca9131f941bba2de6c8/jupyter_releaser/util.py#L123-L128
Here:
https://github.com/jupyter-server/jupyter_releaser/blob/6dd044a248ba4865c4a94ca9131f941bba2de6c8/jupyter_releaser/lib.py#L581
Probably the `branch` was previously not passed down to …
=> Skip branch setup on publish

CHANGELOG.md
Automated Changelog Entry for 0.9.4 on master
| Version Spec | 0.9.4 |
| Since | v1 |
=> Automated Changelog Entry for 0.9.4 on master

.github/actions/draft-release/action.yml, .github/actions/publish-release/action.yml, .github/workflows/draft-changelog.yml, .github/workflows/draft-release.yml, .github/workflows/full-release.yml, .github/workflows/generate-changelog.yml, .github/workflows/test.yml
Clean up the names used in the actions and workflows, and fix the descriptions used for `steps_to_skip`.
=> Clean up actions and workflows

CHANGELOG.md
Automated Changelog Entry for 0.9.6 on master
| Version Spec | 0.9.6 |
| Since | v1 |
=> Automated Changelog Entry for 0.9.6 on master

CHANGELOG.md
Automated Changelog Entry for 0.9.7 on master
| Version Spec | 0.9.7 |
| Since | v1 |
=> Automated Changelog Entry for 0.9.7 on master

CHANGELOG.md
Automated Changelog Entry for 0.9.8 on master
| Version Spec | 0.9.8 |
| Since | v1 |
=> Automated Changelog Entry for 0.9.8 on master

jupyter_releaser/changelog.py
If the only documentation PR(s) were automated, remove that entry from the changelog.
=> Remove empty documentation entry

.github/workflows/draft-changelog.yml
Recently caught when making a release:
=> Fix missing quote in Draft Changelog

docs/source/how_to_guides/convert_repo.md
=> Fix a typo (missing `=`)

docs/source/how_to_guides/write_config.md
The syntax highlighting was kicking in on this one:
Now it will be rendered like a proper list.
=> Beautify rendering of the configuration file list

docs/source/get_started/making_first_release.md, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py
=> Add 'next' convenience for tbump

.github/workflows/draft-changelog.yml, .github/workflows/draft-release.yml, .github/workflows/full-release.yml, .github/workflows/generate-changelog.yml, .github/workflows/publish-release.yml, jupyter_releaser/actions/common.py, jupyter_releaser/actions/generate-changelog.py, jupyter_releaser/changelog.py, jupyter_releaser/lib.py, jupyter_releaser/util.py
=> Make branch and version spec optional

jupyter_releaser/npm.py
At the moment the changelog shows a list of unordered npm packages:
For example: https://github.com/jupyterlab/jupyterlab/pull/11651
This change sorts them so it's a bit more pleasing to the eye.
=> Sort the list of workspace package versions

CHANGELOG.md
Automated Changelog Entry for 0.10.0 on master
| Version Spec | 0.10.0 |
| Since | v1 |
=> Automated Changelog Entry for 0.10.0 on master

CHANGELOG.md
Automated Changelog Entry for 0.10.1 on master
| Since | v1 |
=> Automated Changelog Entry for 0.10.1 on master

jupyter_releaser/changelog.py, jupyter_releaser/tests/util.py, setup.cfg
=> Fix handling of empty documentation header

.github/workflows/test.yml, CONTRIBUTING.md, docs/source/conf.py, docs/source/how_to_guides/convert_repo.md
Looks like the default branch has been renamed to `main`, but some references still need to be updated.
=> Update to the new `main` default branch

jupyter_releaser/util.py
As noticed in https://github.com/jupyterlab/jupyterlab/pull/11770, recent versions of `setuptools` have switched to the Python `logging` infrastructure to log messages. Which means the output of `python setup.py --version` might now contain other messages than just the version.
This is not an issue when using the releaser for now, as there is a pin on `setuptools` here:
https://github.com/jupyter-server/jupyter_releaser/blob/68bb70314fa0347366f79774b8870d4e4f6d419d/setup.cfg#L42
Similar to https://github.com/jupyter-server/jupyter_releaser/pull/37, this changes proposes to parse the last line of the `python setup.py --version` command only.
=> Use the last line of the `python setup.py --version` command to get the Python version

.github/workflows/draft-changelog.yml, .github/workflows/draft-release.yml, .github/workflows/full-release.yml, .github/workflows/generate-changelog.yml, .github/workflows/test.yml, docs/environment.yml, setup.cfg
- Switch from Python `3.9` to `3.10` when testing on CI
- Update trove classifiers
=> Run CI on Python 3.10

jupyter_releaser/cli.py, jupyter_releaser/python.py, jupyter_releaser/tests/conftest.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/util.py
Fixes #237 by allowing to define a Python target to be checked through `python -c "import <target>"` instead of using the package name.
This can be done through a new cli option `--check-imports` or the env variable `RH_CHECK_IMPORTS`.
=> Add configurable python target to check-python

CHANGELOG.md
Automated Changelog Entry for 0.11.0 on main
| Version Spec | 0.11.0 |
| Since | v1 |
=> Automated Changelog Entry for 0.11.0 on main

jupyter_releaser/lib.py
It turns out if you invoke an RST file directly you can't skip the doctests even with the doctest glob option, this is a [workaround](https://github.com/pytest-dev/pytest/issues/4954#issuecomment-478055434)
=> Fix handling of doctest skip

CHANGELOG.md
Automated Changelog Entry for 0.11.1 on main
| Since | v1 |
=> Automated Changelog Entry for 0.11.1 on main

jupyter_releaser/changelog.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/tests/util.py
solves #131 
I'm trying to remove the `...None` from the diff when the changelog is empty. I'm not sure if this is the right solution. I'm a bit lost on how the release works. Meanwhile, I added a test to check if the changelog is empty.
=> Test empty changelog

CHANGELOG.md
Automated Changelog Entry for 0.11.2 on main
| Version Spec | 0.11.2 |
| Since | v1 |
=> Automated Changelog Entry for 0.11.2 on main

jupyter_releaser/lib.py
Ignore pytest config from pyproject.toml, etc.to  avoid conflicts with target package's own pytest config, since we aren't running the package's own tests.
For example, jupyter-server has `addopts = --doctest-modules`, but check-links [now has](https://github.com/jupyter-server/jupyter_releaser/pull/241) `-p no:doctest`, which removes the `--doctest-modules` option, causing `check-links` to [fail](https://github.com/jupyter-server/jupyter_server/runs/4857720531?check_suite_focus=true#step:6:116) on jupyter-server with:
```
pytest: error: unrecognized arguments: --doctest-modules
```
=> ignore package pytest config

CHANGELOG.md
Automated Changelog Entry for 0.11.3 on main
| Since | v1 |
=> Automated Changelog Entry for 0.11.3 on main

.github/workflows/test.yml, docs/source/get_started/making_first_release.md, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py
Fixes #244.  Also changes the way `.dev` versions are handled by "next" - we drop the `.dev` suffix and release a final version.   This had bitten us recently in `jupyter_server`.
=> Add support for minor release

jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/util.py
=> Use a more efficient fetch

jupyter_releaser/changelog.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py
fixes #170 
If the target repository doesn't have tags, select the first commit.
=> Select first commit if there is no tags

jupyter_releaser/actions/publish_release.py
Wait until assets have been published to create the forwardport PR.  This avoids creating multiple PRs if you have to re-run the Publish step due to a credentials error.  cf https://github.com/jupyterlab/jupyterlab/pull/12189#issuecomment-1063532768
=> Create forwardport PR after publishing

CHANGELOG.md
Automated Changelog Entry for 0.13.1 on main
| Since | v1 |
=> Automated Changelog Entry for 0.13.1 on main

CHANGELOG.md
Automated Changelog Entry for 0.13.2 on main
| Since | v1 |
=> Automated Changelog Entry for 0.13.2 on main

jupyter_releaser/cli.py, jupyter_releaser/lib.py
For the quetz-server we need to override the import name with `quetz` (instead of `quetz_server`).
It was otherwise impossible to release.
=> forward python imports for checking with extract_release

CHANGELOG.md
Automated Changelog Entry for 0.13.3 on main
| Since | v1 |
=> Automated Changelog Entry for 0.13.3 on main

.pre-commit-config.yaml, jupyter_releaser/tee.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/tests/util.py, jupyter_releaser/util.py
Useful for flit backends with static version.
=> Support static version in pyproject.toml

CHANGELOG.md
Automated Changelog Entry for 0.14.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.14.0 on main

jupyter_releaser/lib.py
This should fix https://github.com/jupyter-server/jupyter_releaser/issues/278
While investigating the issue that happened during the JupyterLab 4.0.0a23 release: https://github.com/jupyterlab/jupyterlab/issues/12324
It appears the call to `gh.list_tags()` returns a 502 from GitHub.
As posted in https://github.com/jupyterlab/jupyterlab/issues/12324#issuecomment-1085533714, this is reproducible with the following code snippet:
```py
import os
from ghapi.core import GhApi
owner = 'jupyterlab'
repo = 'jupyterlab'
auth = os.getenv('GITHUB_ACCESS_TOKEN')
gh = GhApi(owner=owner, repo=repo, token=auth)
print(gh.list_tags())
```
This is probably happening because the jupyterlab repo has *a lot* of tags (28000+ at the time of writing).
This PR proposes only look for the release tag when listing all …
=> Fix listing of tags

jupyter_releaser/lib.py
Use `python -m pytest` instead of `pytest`.
=> Fix check_links on macOS

CHANGELOG.md
Automated Changelog Entry for 0.15.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.15.0 on main

jupyter_releaser/util.py
cf https://github.com/jupyterlab/jupyterlab/issues/12336
=> Use setup.py --version by default

CHANGELOG.md
Automated Changelog Entry for 0.15.1 on main
| Since | v1 |
=> Automated Changelog Entry for 0.15.1 on main

README.md, docs/source/background/theory.md, docs/source/how_to_guides/write_config.md, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py
Working toward #272.  Allows a simplified handling of dev mode, using the following config:
```toml
[tools.jupyter-releaser.options]
post-version-spec = "dev"
```
=> Improve handling of dev versions

jupyter_releaser/lib.py, jupyter_releaser/tee.py, jupyter_releaser/util.py
We can run with colors and warnings enabled once https://github.com/jupyterlab/pytest-check-links/pull/44 is released.
=> Clean up check links output

CHANGELOG.md
Automated Changelog Entry for 0.16.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.16.0 on main

CHANGELOG.md
Automated Changelog Entry for 0.17.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.17.0 on main

jupyter_releaser/cli.py, jupyter_releaser/util.py
=> Only run check-manifest if using setuptools

CHANGELOG.md
Automated Changelog Entry for 0.18.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.18.0 on main

CHANGELOG.md
Automated Changelog Entry for 0.19.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.19.0 on main

CHANGELOG.md
Automated Changelog Entry for 0.20.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.20.0 on main

jupyter_releaser/lib.py
- Check for pyproject.toml
- Install both dev and test extras (will warn if either do not exist).
=> Fix pip install in git checkout

CHANGELOG.md
Automated Changelog Entry for 0.21.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.21.0 on main

jupyter_releaser/lib.py
=> Check build-system before installing

jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py, pyproject.toml
Fixes issue seen in https://github.com/jupyter/notebook/pull/6448 where `releaser` tries to use `python setup.py --version` to get the file, when it should be using `hatchling.version`.
=> Add hatchling handling

CHANGELOG.md
Automated Changelog Entry for 0.22.1 on main
| Since | v1 |
=> Automated Changelog Entry for 0.22.1 on main

jupyter_releaser/util.py
This PR add a return value when getting version by building wheel, which is missing in the latest version of jupyter_releaser.
=> Fix a bug when retrieving package version

CHANGELOG.md
Automated Changelog Entry for 0.22.2 on main
| Since | v1 |
=> Automated Changelog Entry for 0.22.2 on main

jupyter_releaser/actions/draft_release.py, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py
=> Fix handling of versions when dev versions are used

CHANGELOG.md
Automated Changelog Entry for 0.22.4 on main
| Since | v1 |
=> Automated Changelog Entry for 0.22.4 on main

.github/actions/draft-release/action.yml, .github/workflows/check-release.yml, docs/source/conf.py, docs/source/get_started/making_first_release.md, jupyter_releaser/__init__.py, jupyter_releaser/actions/draft_release.py, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py, pyproject.toml
For now we disallow the use of "next" or "patch" when dev versions are used, until we can implement a proper fix as part of #272
=> Revert changes to handle dev versions

CHANGELOG.md
Automated Changelog Entry for 0.22.5 on main
| Version Spec | 0.22.5 |
| Since | v1 |
=> Automated Changelog Entry for 0.22.5 on main

pyproject.toml
To avoid accidentally bumping a dependency version
=> Use version template in pyproject

.github/actions/check-release/action.yml, jupyter_releaser/actions/common.py, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/mock_github.py, jupyter_releaser/tests/conftest.py, jupyter_releaser/util.py
=> Use mock github when in dry run mode

jupyter_releaser/lib.py, jupyter_releaser/util.py
=> Use bare git for dry run

CHANGELOG.md, jupyter_releaser/lib.py
Automated Changelog Entry for 0.23.0 on main
| Since | v1 |
=> Automated Changelog Entry for 0.23.0 on main

jupyter_releaser/lib.py
In #358, the logic to create the changelog PR was updated to use `git merge` instead `git stash` (presumably to be more robust in case of changes are pulled from the upstream branch).
In JupyterLab, this results in the bump by lerna of node packages to be committed with the Changelog changes as a commit is done automatically by lerna in the bump version step. The reason is that the merge command on the stash branch is bringing in more than the change stashed.
Failing PR example: https://github.com/jupyterlab/jupyterlab/pull/12932
=> Revert to using stash apply instead of merge

CHANGELOG.md
Automated Changelog Entry for 0.23.1 on main
| Since | v1 |
=> Automated Changelog Entry for 0.23.1 on main

CHANGELOG.md
Automated Changelog Entry for 0.23.2 on main
| Since | v1 |
=> Automated Changelog Entry for 0.23.2 on main

.github/workflows/full-release.yml, pyproject.toml
Fixes a typo in *.github/workflows/full-release.yml*, which makes the `since_last_stable` parameter unusable (and causes the job to fail if the *changelog* was built using this parameter).
=> Fix the input parameter since_last_stable when running a full release

CHANGELOG.md
Automated Changelog Entry for 0.23.3 on main
| Since | v1 |
=> Automated Changelog Entry for 0.23.3 on main

docs/source/conf.py, jupyter_releaser/util.py, pyproject.toml
Use "hatch version" as a default if there is no tbump config.
Will have to wait for #363 to be merged.
=> Use "hatchling version" as a version command where applicable

.github/workflows/full-release.yml, jupyter_releaser/lib.py, jupyter_releaser/util.py
This fixes is based on using the new version to release JLab 3.4.7:
- `target` not pass to _publish-release_
Should we pass `steps_to_skip` too? It seems not as there is only one step - so probably that input should be remove from standalone workflow _Publish Release_
- `metadata.json` was not ignored from the sha check loop
> I created a constant storing `metadata.json` in `util.py`.
=> Fix publish-release

CHANGELOG.md
Automated Changelog Entry for 0.24.0 on main
| Draft Release | https://github.com/jupyter-server/jupyter_releaser/releases/tag/untagged-d679f854d7a99152cf06  |
| Since | v1 |
=> Automated Changelog Entry for 0.24.0 on main

CHANGELOG.md
Automated Changelog Entry for 0.24.1 on main
| Draft Release | https://github.com/jupyter-server/jupyter_releaser/releases/tag/untagged-594ef5081ee407858cc6  |
| Since | v1 |
=> Automated Changelog Entry for 0.24.1 on main

jupyter_releaser/cli.py, jupyter_releaser/util.py
Fixes #384 
Also adds logging for the values, to help diagnosing things like #385
=> Clean up handling of draft release metadata

CHANGELOG.md
Automated Changelog Entry for 0.24.2 on main
| Draft Release | https://github.com/jupyter-server/jupyter_releaser/releases/tag/untagged-483f32cce75028e2c449  |
| Since | v1 |
=> Automated Changelog Entry for 0.24.2 on main

jupyter_releaser/cli.py
Fixes #335 and a bug in the last release.
=> Fix handling of check manifest

CHANGELOG.md
Automated Changelog Entry for 0.24.3 on main
| Draft Release | https://github.com/jupyter-server/jupyter_releaser/releases/tag/untagged-5576f3a21764e6b3ffc0  |
| Since | v1 |
=> Automated Changelog Entry for 0.24.3 on main

jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/python.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/util.py, jupyter_releaser/util.py
Include the shas of the files when uploading.  Compare against those shas in extract release rather than against the commit message.  Also do not re-check the dist files since we already did that before uploading.
=> Clean up Extract Release

.github/workflows/prep-release.yml, .github/workflows/publish-release.yml, jupyter_releaser/actions/populate_release.py, jupyter_releaser/lib.py, jupyter_releaser/util.py
Create a new file so we do not hit a 422 error when trying to re-upload `metadata.json`.  This is cleaner anyway since the metadata file becomes environment variables.
I'm testing the version2 workflows with https://github.com/blink1073/test-python-project.  So far prep release worked but publish release failed with the 422 error.
=> Clean up asset sha handling

CHANGELOG.md
Automated Changelog Entry for 0.25.0 on main
| Draft Release | https://github.com/jupyter-server/jupyter_releaser/releases/tag/untagged-d97c915a9e1c035dfa0e  |
| Since | v1 |
=> Automated Changelog Entry for 0.25.0 on main

.pre-commit-config.yaml, CHANGELOG.md, jupyter_releaser/lib.py, pyproject.toml
Format the entry from the draft GitHub release before writing it to the changelog file to prevent linting errors.
=> Run mdformat on the manually formatted changelog entry

.github/workflows/prep-release.yml, .github/workflows/publish-release.yml, README.md, docs/source/how_to_guides/convert_repo_from_repo.md, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/util.py
Reverts jupyter-server/jupyter_releaser#424
It prevents making a release from a fork of `jupyter_releaser`.
=> Revert "Better handling of git actor"

jupyter_releaser/util.py
We are looking at the wrong remote branches, this will need fixing.
=> Stop erroring on ensure_sha for now

README.md, jupyter_releaser/actions/populate_release.py, jupyter_releaser/util.py
Fixes #421.  We were running it before we had a git checkout.
=> Fix ensure_sha

.github/workflows/prep-release.yml, .github/workflows/publish-release.yml, docs/source/how_to_guides/convert_repo_from_repo.md
But still enforce that the triggering actor has admin permissions.
=> Use admin token

.github/actions/finalize-release/action.yml, .github/actions/populate-release/action.yml, .github/actions/prep-release/action.yml, .github/workflows/prep-release.yml, .github/workflows/publish-release.yml, .pre-commit-config.yaml, docs/source/get_started/making_release_from_repo.md, docs/source/how_to_guides/convert_repo_from_repo.md, example-workflows/prep-release.yml, example-workflows/publish-release.yml, jupyter_releaser/util.py
=> Simplify security handling

.github/workflows/check-release.yml, .github/workflows/test.yml, jupyter_releaser/__init__.py, jupyter_releaser/changelog.py, jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/util.py, pyproject.toml
Make use of the `validate-bump` option in [hatch](https://hatch.pypa.io/latest/plugins/version-scheme/standard/)
Fixes #398
=> Allow dev versions

docs/source/how_to_guides/convert_repo_from_releaser.md, docs/source/how_to_guides/convert_repo_from_repo.md, example-workflows/prep-release.yml, example-workflows/publish-release.yml
=> Update how-to guides

.github/workflows/test.yml, jupyter_releaser/lib.py, jupyter_releaser/mock_github.py, jupyter_releaser/python.py, jupyter_releaser/tests/conftest.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/util.py, pyproject.toml
Follow advice from https://github.com/zupo/awesome-pytest-speedup
Locally the full test suite went from 200s -> 56s.
=> Improve test speed

jupyter_releaser/lib.py
=> Do no install the package by default

docs/source/how_to_guides/convert_repo_from_repo.md
The bot account needs to be an admin on the target repo
=> Update conversion instructions

jupyter_releaser/util.py
Attempt at fixing https://github.com/jupyter-server/jupyter_releaser/pull/444/files#r999693330
Otherwise it looks like a file named `GITHUB_OUTPUT` is being created on disk: https://github.com/jupyter/notebook/pull/6579#issuecomment-1283931797
=> Fix handling of `GITHUB_OUTPUT`

.github/workflows/check-release.yml, .github/workflows/generate-changelog.yml, .github/workflows/prep-release.yml, .github/workflows/publish-release.yml, .github/workflows/test.yml
Fixes the following warning reported as annotation:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
```
=> Update to `actions/checkout@v3`

jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/test_functions.py, jupyter_releaser/tests/util.py, jupyter_releaser/util.py
=> Fix handling of dev mode

docs/source/how_to_guides/convert_repo_from_releaser.md
Not sure what was the intent here, but formatting is wrong so I guess copy-paste issue.
=> Fix typo(?) 2

.github/workflows/generate-changelog.yml, jupyter_releaser/actions/generate_changelog.py, jupyter_releaser/util.py
=> Add since_last_stable support in generate changelog

docs/source/conf.py
Nicer rerndering of tasks lists in docs see https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#task-lists
| Before | After |
|---|---|
| ![Screenshot from 2022-12-28 14-51-13](https://user-images.githubusercontent.com/5832902/209830056-4fd8fd20-a1f2-477f-b9c3-fc8f6c15b407.png) | ![Screenshot from 2022-12-28 14-50-59](https://user-images.githubusercontent.com/5832902/209830081-4aaa7e78-4d5b-41bb-bea2-097ff7072f56.png) |
=> Enable tasklist myst extension

.github/actions/check-release/action.yml
Working at updating `jlpm` to yarn3, the check release action is failing because yarn3 does not allow accessing an `http` resource without whitelist setting.
Would it be possible to add a new tagged version including this ?
=> Add whitelist for http request in yarn

example-workflows/prep-release.yml, example-workflows/publish-release.yml
It looks like the `prep-release.yml` and `publish-release.yml` workflows don't have an input called `target`.
=> Remove `target` from the example releaser workflows

example-workflows/full-release.yml
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/175
For small projects where we don't necessarily need to check the changelog, it can be convenient to make a release in one go using a single workflow.
This PR adds a `full-release.yml` workflow to the `example-workflows` folder called `Step 1 + 2: Full Release`. Happy to go with another name if needed.
Generally we should still encourage the 2 steps approach to allow for checking the new version numbers and changelog are correct. So it's not mentioned in the documentation for now but could be added if folks find it useful.
Here is an example run of such workflow: https://github.com/jtpio/ipylab/actions/runs/4561211046/jobs/8046913448
cc @martinRenou
=> Add a Full Release workflow to the example workflows

.github/actions/finalize-release/action.yml
It looks like that action install the wrong version of the package.
=> Fix package version target

docs/source/conf.py
When clicking on the edition link on read the docs, we are currently redirected to `jupyterlab/jupyterlab_server`. This fixes it.
=> Fix doc edition links

jupyter_releaser/npm.py
Fix issue seen in https://github.com/jupyterlab-contrib/jupyterlab-favorites/pull/15
=> Only run npm pack if there are public packages in workspace

jupyter_releaser/npm.py
Bug seen in https://github.com/jupyter/nbdime/actions/runs/6523856857/job/17714912280?pr=710 where one of the package is private and does not have a version.
=> Don't tag private package or pkg without version

.github/workflows/test.yml, .pre-commit-config.yaml, .readthedocs.yml, docs/source/conf.py, docs/source/how_to_guides/write_config.md, jupyter_releaser/actions/generate_changelog.py, jupyter_releaser/changelog.py, jupyter_releaser/mock_github.py, jupyter_releaser/python.py, jupyter_releaser/tee.py, jupyter_releaser/tests/conftest.py, jupyter_releaser/tests/test_cli.py, jupyter_releaser/tests/util.py, jupyter_releaser/util.py, pyproject.toml
Adds minimal sp-repo-review.  Will save typings and moving the tests folder for after #521
=> Adopt ruff format and sp-repo-review

jupyter_releaser/cli.py, jupyter_releaser/lib.py, jupyter_releaser/tests/test_cli.py
This has been seen by @vidartf in https://github.com/jupyter/nbdime/issues/659#issuecomment-1816245117
It add the option tag format to allow commands make use of the tag name.
=> Allow the tag format customization

.github/workflows/publish-changelog.yml, example-workflows/publish-changelog.yml
See on https://github.com/jupyterlab/jupyterlab/pull/15446 by @krassowski
=> Remove unneeded token from workflow inputs

jupyter_releaser/cli.py, jupyter_releaser/npm.py, jupyter_releaser/tests/conftest.py, jupyter_releaser/tests/util.py
When publishing JupyterLab with the NPM provenance feature, it failed because the package.json file was not defining a proper `repository.url`. This adds a test for it in `check-npm-dist`
=> Add test for repository.url

jupyter_releaser/npm.py
Bug seen in https://github.com/jupyterlab/lumino/actions/runs/7170712609/job/19524081611?pr=664
The buildutils package of lumino defines its repository as a string (this is [valid](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository))
https://github.com/jupyterlab/lumino/blob/744b258922173ca80bb6ec9718732ff437ebf75b/buildutils/package.json#L10
Test for the type of _repository_
=> Fix string repository

.github/actions/check-release/action.yml, .github/actions/finalize-release/action.yml, .github/actions/populate-release/action.yml, .github/actions/prep-release/action.yml, .github/actions/publish-changelog/action.yml
Discovered in https://github.com/voila-dashboards/voici/pull/107
It seems that when using a mamba-installed yarn (v3) it is not being picked up by the releaser. I understand the issue has to do with the shell being used in the jupyter-releaser action, so making this one configurable could allow to fix it
=> Allow customizing the shell for the action

jupyter_releaser/lib.py, tests/test_cli.py
* When py packages names are inconsistent between jupyter releaser config and wheel, uploading assets to PyPI will be silently skipped. We emit a warning now when this happens
* A unit test has been added to test the warning
Closes #554
=> Emit a warning when uploading is skipped

.github/workflows/prep-self-release.yml, .github/workflows/publish-changelog.yml, .github/workflows/publish-self-release.yml, docs/source/background/theory.md, docs/source/how_to_guides/convert_repo_from_repo.md, docs/source/how_to_guides/maintain_fork.md, example-workflows/full-release.yml, example-workflows/prep-release.yml, example-workflows/publish-changelog.yml, example-workflows/publish-release.yml
=> Remove the need for an ADMIN_GITHUB_TOKEN

.github/actions/publish-changelog/action.yml
This action is run with the credentials of the GitHub App, so it will not have admin credentials: https://github.com/jupyter/nbformat/actions/runs/8250694185/job/22565921338
=> Do not require admin for publish changelog action

jupyter_releaser/lib.py
(if it is not a previously published version error)
https://github.com/jupyter-server/jupyter_releaser/issues/563
Of note, lack of the error message here has wasted a number of hours with other npm upload issues previously (e.g. when npm was down, or npm account was mis-configured).
=> Print out error for npm upload

jupyter_releaser/lib.py
This should help with https://github.com/jupyterlab/jupyter-collaboration/issues/265#issuecomment-2058916408 - does it seem right? I always thought that dashes are preferred in package names over underscores and the https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#name gives an example of `spam-eggs`
=> Normalise package name before comparison

jupyter_releaser/cli.py, jupyter_releaser/lib.py
This aims to alleviate https://github.com/jupyter-server/jupyter_releaser/issues/567#issuecomment-2067274319 by checking for package-specific tags. As of today it effectively, skips the check for already existing tags when:
- package names are defined for python packages, **and**
- there is more than one python package
It does not implement creating tags per Python package yet.
=> Prepend tag with Python package name if multiple packages are defined

docs/source/get_started/making_release_from_repo.md, docs/source/how_to_guides/convert_repo_from_repo.md
Drop legacy PyPI
Update trusted publisher set up to use the required `release` GH environment
Mention hatch instead of tbump
=> Improve documentation

jupyter_releaser/cli.py
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/571
There are three difficult things in programming: naming things and off by one errors.
=> Fix `maxsplit` usage

docs/source/how_to_guides/convert_repo_from_repo.md
GitHub authentication is now done through an application.
=> Remove the GitHub access token prerequisite

jupyter_releaser/lib.py, tests/test_cli.py
=> Fix handling of workflow branch

README.md
The current indentation looks a bit off:
=> Fix code indentation in README.md

docs/source/conf.py
Just a tiny QoL improvements (when looking at docs I often want to double check things in code)
=> Add link to GitHub repo in docs navbar

docs/source/faq/index.md
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/584
=> Add more content to the FAQ

docs/source/faq/index.md
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/508
For now the FAQ seems to be a good place to put this kind of information. But it could be moved to another section of the docs later if needed.
=> Add FAQ section about publish to `npm` only

docs/source/index.md
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/459
This provides a high level overview of the releaser. It also makes it easier to find the link to the blog post from the docs.
=> Add link to the blog post to the documentation

.github/workflows/test.yml, pyproject.toml
Fixes https://github.com/jupyter-server/jupyter_releaser/issues/595, workaround for https://github.com/pypiserver/pypiserver/issues/630.
Closes https://github.com/jupyter-server/jupyter_releaser/pull/594
=> Pin `pypiserver` to v2.2.0

CONTRIBUTING.md, jupyter_releaser/cli.py
I wanted to run the command in bar folder
```
jupyter-releaser build-python --help
```
This line is in the `README.md`, so it should work right away.
But it gave an error
```
File "/home/rakhmaevao/Projects/jupyter_releaser/jupyter_releaser/cli.py", line 44, in invoke
raise ValueError(msg)
ValueError: Please run prep-git first
```
I fixed it.
Also the command to run tests from the `CONTRIBUTING.md` file did not work. But another command works. I fixed the `CONTRIBUTING.md` file.
=> Fix for displaying help for the `build_python` command

.github/workflows/test.yml
As seen in https://github.com/jupyter-server/jupyter_releaser/pull/607, the CI no longer runs. This should fix it.
=> Replace `ubuntu-20.04` runners with `ubuntu-latest`

.github/workflows/test.yml, pyproject.toml
Python 3.8 is EOL, CI is failing on Python 3.8.
https://github.com/jupyter-server/jupyter_releaser/pull/608#issuecomment-2871802251
=> Require Python 3.9+, test on Python 3.9 and 3.13

jupyter_releaser/lib.py
This PR fixes an issue where previously published packages are not recognized for other npm registries, such as GitHub packages.
Closes #603 .
=> Check for `npm` error code 409 to skip previously published packages in private registries
