.github/workflows/draft-changelog.yml
jupyter_releaser/cli.py
jupyter_releaser/lib.py
jupyter_releaser/tests/test_cli.py

- Handle options with list values
- Always ignore certain links
- Check links one file at a time and allow there to be no links
- Use admin token for Draft Changelog since it has to create a new branch

More Cleanup

---

.github/workflows/check-release.yml
.github/workflows/draft-changelog.yml
.github/workflows/draft-release.yml
.github/workflows/publish-release.yml
.github/workflows/test.yml
README.md
jupyter_releaser/actions/publish_release.py
jupyter_releaser/cli.py
jupyter_releaser/lib.py
jupyter_releaser/tests/test_cli.py
jupyter_releaser/util.py
setup.cfg

Fixes https://github.com/jupyter-server/jupyter_releaser/issues/7
Also cleans up workflows and normalizes `print()` handling

Use Local PyPI Server for Dry Run

---

.github/actions/check-release/action.yml

Add missing to install from upstream repo

---

README.md

This will allow the ReadMe to render the images on PyPI

Use raw GitHub Links

---

CHANGELOG.md

Automated Changelog Entry for 0.1.0 on master
After merging this PR run the "Draft Release" Workflow with the following inputs
| Version Spec | 0.1.0 |

Automated Changelog Entry for 0.1.0 on master

---

CHANGELOG.md

Automated Changelog Entry for 0.1.3 on master
| Version Spec | 0.1.3 |

Automated Changelog Entry for 0.1.3 on master

---

CHANGELOG.md

Automated Changelog Entry for 0.1.4 on master
| Version Spec | 0.1.4 |

Automated Changelog Entry for 0.1.4 on master

---

CHANGELOG.md

Automated Changelog Entry for 0.1.5 on master
| Version Spec | 0.1.5 |

Automated Changelog Entry for 0.1.5 on master

---

jupyter_releaser/npm.py

Fix the ability to publish npm packages as part of the automated release process. Follow the formatting guidelines from [npm](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow)

Fix handling of npm token

---

CHANGELOG.md

Automated Changelog Entry for 0.1.7 on master
| Version Spec | 0.1.7 |

Automated Changelog Entry for 0.1.7 on master

---

jupyter_releaser/lib.py

Install yarn if it is not already installed

---

jupyter_releaser/util.py

Handle missing version from package.json in `get_version`

---

jupyter_releaser/lib.py
jupyter_releaser/tests/test_functions.py
setup.cfg

Add missing `return` to `draft_changelog`

---

CHANGELOG.md

Automated Changelog Entry for 0.1.17 on master
| Version Spec | 0.1.17 |

Automated Changelog Entry for 0.1.17 on master

---

jupyter_releaser/lib.py

This should fix check release workflow failures on pull requests.

Handle commit message failure

---

.github/actions/check-release/action.yml

Fix installing the releaser in the check release workflow

---

CHANGELOG.md

Automated Changelog Entry for 0.3.1 on master
| Version Spec | 0.3.1 |

Automated Changelog Entry for 0.3.1 on master

---

.github/actions/check-links/action.yml
.github/actions/check-release/action.yml
jupyter_releaser/actions/draft_release.py
jupyter_releaser/lib.py
jupyter_releaser/python.py
jupyter_releaser/tests/test_cli.py
jupyter_releaser/util.py

Make the output quieter so it is easier to read

Clean up build output

---

.github/actions/check-release/action.yml
README.md
jupyter_releaser/cli.py
jupyter_releaser/lib.py
jupyter_releaser/tests/conftest.py
jupyter_releaser/tests/test_cli.py
jupyter_releaser/tests/test_functions.py
jupyter_releaser/tests/util.py
jupyter_releaser/util.py

- Allows hooks to be used during the publish action
- Adds testing for all hooks

Fix up hook handling

---

CHANGELOG.md

Automated Changelog Entry for 0.4.2 on master
| Version Spec | 0.4.2 |

Automated Changelog Entry for 0.4.2 on master

---

jupyter_releaser/changelog.py

Fixes error introduced in https://github.com/jupyter-server/jupyter_releaser/pull/102 that used the wrong branch target for `github_activity` resulting in no found [PRs](https://github.com/jupyterlab/jupyterlab_server/pull/196).

Fix Changelog Build

---

CHANGELOG.md

Automated Changelog Entry for 0.4.4 on master
| Version Spec | 0.4.4 |

Automated Changelog Entry for 0.4.4 on master

---

.github/workflows/test.yml
jupyter_releaser/changelog.py
jupyter_releaser/tests/test_functions.py

Follow up to jupyter-server/jupyter_releaser#116

Fix usage of since parameter

---

jupyter_releaser/lib.py
jupyter_releaser/npm.py
jupyter_releaser/tests/test_functions.py

- Adds ability to use config during `extract_release`
- Fixes handling of npm config for login

Fix Extract Release Config and Npm Config Handling

---

jupyter_releaser/npm.py

Better handling of `npm` workspace packages - pack them all at once and do not print the tags when listing

Clean up NPM Package Handling

---

jupyter_releaser/lib.py
jupyter_releaser/npm.py
jupyter_releaser/python.py
jupyter_releaser/tests/conftest.py
jupyter_releaser/tests/util.py
jupyter_releaser/util.py

Make more outputs quiet in CI and tests

Quieter Output Again

---

jupyter_releaser/util.py

Follow-up to https://github.com/jupyter-server/jupyter_releaser/pull/134
Attempt at fixing https://github.com/jupyter-server/jupyter_releaser/pull/134/files#r703631330

Fix handling of releaser config in multiple files

---

jupyter_releaser/util.py

Alternative to https://github.com/jupyter-server/jupyter_releaser/pull/139 as a folllow-up to #138.

Read the schema on import

---

.github/workflows/publish-release.yml
jupyter_releaser/cli.py
jupyter_releaser/lib.py
jupyter_releaser/tests/test_cli.py

Set the npm and pypi registry values in settings instead of using workflow inputs

Move registry options to settings

---

.github/workflows/autopublish-release.yml

Fix auto publish workflow indent

---

.github/actions/draft-release/action.yml

Fix typo in the draft release action

---

jupyter_releaser/actions/publish_release.py
jupyter_releaser/util.py

- Fix bug in twine password handling
- Fail after 3 attempts in the retry utility

Publish Fixes

---

jupyter_releaser/actions/draft_changelog.py
jupyter_releaser/actions/draft_release.py
jupyter_releaser/changelog.py
jupyter_releaser/util.py

Fix capture of "since" tag to take into account the "since last stable" input

Fix Handling of Since Last Stable

---

jupyter_releaser/util.py

Needed for https://github.com/jupyterlab/maintainer-tools/pull/7

Allow for a single private package

---

jupyter_releaser/lib.py
jupyter_releaser/tests/test_cli.py

Allow publish with no assets

---

jupyter_releaser/lib.py

Improve Python multi-package handling

---

jupyter_releaser/tests/test_functions.py
jupyter_releaser/util.py

Fixes error seen in https://github.com/jupyter-server/jupyter_server/runs/4523603783?check_suite_focus=true

Fix handling of dev version in version bump

---

CHANGELOG.md

Automated Changelog Entry for 0.10.2 on master
| Since | v1 |

Automated Changelog Entry for 0.10.2 on master

---

setup.cfg

Mostly for consistency and to prepare for https://github.com/conda-forge/staged-recipes/pull/16123

Update to `tbump~=6.7`

---

jupyter_releaser/cli.py
jupyter_releaser/lib.py
jupyter_releaser/python.py
jupyter_releaser/tests/test_cli.py

Make twine check strict by default

---

jupyter_releaser/lib.py
jupyter_releaser/tests/test_cli.py
jupyter_releaser/tests/util.py

Add documentation label to changelog PR

---

jupyter_releaser/actions/publish_release.py

Forwardport changelog before publishing github release

---

.github/workflows/test.yml
setup.cfg

Workaround for https://github.com/pypa/setuptools/issues/3200
Fixes #269

Include explicit package data

---

.github/workflows/draft-changelog.yml
.github/workflows/draft-release.yml
.github/workflows/full-release.yml
.github/workflows/generate-changelog.yml
jupyter_releaser/actions/check_links.py
jupyter_releaser/actions/common.py
jupyter_releaser/actions/draft_changelog.py
jupyter_releaser/actions/draft_release.py
jupyter_releaser/actions/generate-changelog.py
jupyter_releaser/actions/publish_release.py

Use print groups and input types

---

.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.md
jupyter_releaser/actions/check_links.py
jupyter_releaser/actions/draft_changelog.py
jupyter_releaser/actions/draft_release.py
jupyter_releaser/actions/generate-changelog.py
jupyter_releaser/changelog.py
jupyter_releaser/cli.py
jupyter_releaser/lib.py
jupyter_releaser/python.py
jupyter_releaser/tee.py
jupyter_releaser/tests/conftest.py
jupyter_releaser/tests/test_cli.py
jupyter_releaser/tests/test_functions.py
jupyter_releaser/tests/util.py
jupyter_releaser/util.py
setup.cfg

- Use pre-commit config from `jupyter_server`
- Use flake8 config from `jupyter_server`
- Make some checks manual, running in CI only by default

Clean up pre-commit

---

jupyter_releaser/changelog.py
jupyter_releaser/tests/test_functions.py
jupyter_releaser/tests/util.py

Add ability to splice github release entry

---

.github/workflows/draft-changelog.yml
.github/workflows/draft-release.yml
.github/workflows/full-release.yml
.github/workflows/generate-changelog.yml
.github/workflows/publish-release.yml
.github/workflows/test.yml
.pre-commit-config.yaml
MANIFEST.in
docs/source/conf.py
jupyter_releaser/actions/draft_changelog.py
jupyter_releaser/actions/draft_release.py
jupyter_releaser/cli.py
jupyter_releaser/lib.py
jupyter_releaser/npm.py
jupyter_releaser/python.py
jupyter_releaser/tee.py
jupyter_releaser/tests/conftest.py
jupyter_releaser/tests/test_cli.py
jupyter_releaser/tests/test_functions.py
jupyter_releaser/tests/util.py
jupyter_releaser/util.py
pyproject.toml
setup.py

Also ignore docs.github.com links since they give 403 errors outside of a browser context now

Clean up pytest and add mypy handling

---

jupyter_releaser/tests/test_functions.py
jupyter_releaser/tests/util.py
jupyter_releaser/util.py

Add a utility to get the latest draft release for a given repo

---

jupyter_releaser/changelog.py
jupyter_releaser/tests/test_cli.py

Handle manual backport PRs

---

pyproject.toml

Handle license

---

.github/workflows/draft-changelog.yml
.github/workflows/draft-release.yml
.github/workflows/full-release.yml
.github/workflows/publish-release.yml

ref https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

Highlight next step using GitHub step summary

---

jupyter_releaser/util.py

Addresses https://github.com/jupyter-server/jupyter_releaser/pull/372#issuecomment-1243996752

Get repository from release url if given

---

jupyter_releaser/actions/common.py

Fix handling of fetch_draft_release param

---

jupyter_releaser/actions/populate_release.py

Ensure proper ghAPI object setup.

Fix handling of asset_shas check

---

jupyter_releaser/cli.py

Fix default twine registry

---

jupyter_releaser/cli.py

Follow up to #408, had the wrong url

fix default registry again

---

jupyter_releaser/util.py

Try fixing admin handling

---

jupyter_releaser/util.py

Prevents pipx warnings in logs.

Use global hatch if available

---

jupyter_releaser/util.py

cf https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
h/t @gabalafou

Update handling of action outputs

---

docs/source/get_started/making_release_from_repo.md

Add docs for starting making prereleases

---

.github/workflows/test.yml
.pre-commit-config.yaml
codecov.yml
jupyter_releaser/tests/conftest.py
pyproject.toml

Clean up workflows, pre-commit, coverage, pyproject

CI Cleanup

---

jupyter_releaser/util.py

Related to https://github.com/jupyter-server/jupyter_releaser/issues/474#issuecomment-1345595689

Add log when loading configuration

---

jupyter_releaser/changelog.py
jupyter_releaser/lib.py

Pass the authentication to `format_pr_entry`

---

.github/workflows/prep-self-release.yml
.github/workflows/publish-self-release.yml

Add workflows to release releaser itself with trusted publishing.

Add trusted publishing and self release

---

.github/actions/check-release/action.yml
.github/actions/finalize-release/action.yml
.github/actions/install-releaser/action.yml
.github/actions/populate-release/action.yml
.github/actions/prep-release/action.yml
.github/actions/publish-changelog/action.yml
.github/scripts/install-releaser.sh

Install the current checkout of releaser if it is not installed.  This makes it easier to test branches.

Fix install releaser step

---

docs/source/get_started/making_release_from_repo.md

Point to updated instructions in adoption checklist.

Update Getting Started Guide

---

.github/workflows/test.yml

Noticed by @brichet in https://github.com/jupyter-server/jupyter_releaser/pull/596#issuecomment-2500950707

Fix "test minimum versions" job
